// src/data/youtube.js

export const videoData = {
  Trending: [
    {
      id: "fLexgOxsZu0",
      title: "Pharrell Williams - Happy",
      channelTitle: "PharrellWilliams",
      channelAvatar: "https://i.pravatar.cc/100?img=32",
      thumbnail: "https://i.ytimg.com/vi/fLexgOxsZu0/hq720.jpg",
      views: 1100000000,
      publishedAt: "2013-11-21T00:00:00Z",
      description: "Official music video for “Happy” by Pharrell Williams.",
      tags: ["Trending"],
      category: "Trending",
      duration: "3:53",
    },
    {
      id: "RgKAFK5djSk",
      title: "Wiz Khalifa - See You Again ft. Charlie Puth",
      channelTitle: "Wiz Khalifa",
      channelAvatar: "https://i.pravatar.cc/100?img=33",
      thumbnail: "https://i.ytimg.com/vi/RgKAFK5djSk/hq720.jpg",
      views: 5000000000,
      publishedAt: "2015-04-06T00:00:00Z",
      description: "“See You Again” – official video by Wiz Khalifa ft. Charlie Puth.",
      tags: ["Trending"],
      category: "Trending",
      duration: "3:55",
    },
    {
      id: "OPf0YbXqDm0",
      title: "Mark Ronson - Uptown Funk ft. Bruno Mars",
      channelTitle: "MarkRonsonVEVO",
      channelAvatar: "https://i.pravatar.cc/100?img=34",
      thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/hq720.jpg",
      views: 4500000000,
      publishedAt: "2014-11-19T00:00:00Z",
      description: "Official video for “Uptown Funk” by Mark Ronson ft. Bruno Mars.",
      tags: ["Trending"],
      category: "Trending",
      duration: "4:30",
    },
    
    {
      id: "uelHwf8o7_U",
      title: "Eminem - Love The Way You Lie ft. Rihanna",
      channelTitle: "EminemVEVO",
      channelAvatar: "https://i.pravatar.cc/100?img=35",
      thumbnail: "https://i.ytimg.com/vi/uelHwf8o7_U/hq720.jpg",
      views: 1900000000,
      publishedAt: "2010-08-05T00:00:00Z",
      description: "“Love The Way You Lie” – Eminem ft. Rihanna official video.",
      tags: ["Trending"],
      category: "Trending",
      duration: "4:23",
    },
    {
      id: "60ItHLz5WEA",
      title: "Alan Walker - Faded",
      channelTitle: "Alan Walker",
      channelAvatar: "https://i.pravatar.cc/100?img=37",
      thumbnail: "https://i.ytimg.com/vi/60ItHLz5WEA/hq720.jpg",
      views: 3400000000,
      publishedAt: "2015-12-03T00:00:00Z",
      description: "Official music video for “Faded” by Alan Walker.",
      tags: ["Trending"],
      category: "Trending",
      duration: "3:32",
    },
    {
      id: "YQHsXMglC9A",
      title: "Adele - Hello (Live)",
      channelTitle: "Adele",
      channelAvatar: "https://i.pravatar.cc/100?img=39",
      thumbnail: "https://i.ytimg.com/vi/YQHsXMglC9A/hq720.jpg",
      views: 2200000000,
      publishedAt: "2015-10-23T00:00:00Z",
      description: "Live performance of “Hello” by Adele.",
      tags: ["Trending"],
      category: "Trending",
      duration: "6:07",
    },
    {
      id: "fRh_vgS2dFE",
      title: "Justin Bieber - Sorry",
      channelTitle: "JustinBieberVEVO",
      channelAvatar: "https://i.pravatar.cc/100?img=40",
      thumbnail: "https://i.ytimg.com/vi/fRh_vgS2dFE/hq720.jpg",
      views: 3700000000,
      publishedAt: "2015-10-22T00:00:00Z",
      description: "Official music video for “Sorry” by Justin Bieber.",
      tags: ["Trending"],
      category: "Trending",
      duration: "3:25",
    },
    {
    id: 'fLexgOxsZu0',
    title: 'Pharrell Williams - Happy',
    channelTitle: 'PharrellWilliams',
    channelAvatar: 'https://i.pravatar.cc/100?img=32',
    thumbnail: 'https://i.ytimg.com/vi/fLexgOxsZu0/hq720.jpg',
    views: 1100000000,
    publishedAt: '2013-11-21T00:00:00Z',
    description: 'Official music video for “Happy” by Pharrell Williams.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '3:53',
  },
  {
    id: 'RgKAFK5djSk',
    title: 'Wiz Khalifa - See You Again ft. Charlie Puth',
    channelTitle: 'Wiz Khalifa',
    channelAvatar: 'https://i.pravatar.cc/100?img=33',
    thumbnail: 'https://i.ytimg.com/vi/RgKAFK5djSk/hq720.jpg',
    views: 5000000000,
    publishedAt: '2015-04-06T00:00:00Z',
    description: '“See You Again” – official video by Wiz Khalifa ft. Charlie Puth.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '3:55',
  },
  {
    id: 'OPf0YbXqDm0',
    title: 'Mark Ronson - Uptown Funk ft. Bruno Mars',
    channelTitle: 'MarkRonsonVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=34',
    thumbnail: 'https://i.ytimg.com/vi/OPf0YbXqDm0/hq720.jpg',
    views: 4500000000,
    publishedAt: '2014-11-19T00:00:00Z',
    description: 'Official video for “Uptown Funk” by Mark Ronson ft. Bruno Mars.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '4:30',
  },
  {
    id: 'uelHwf8o7_U',
    title: 'Eminem - Love The Way You Lie ft. Rihanna',
    channelTitle: 'EminemVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=35',
    thumbnail: 'https://i.ytimg.com/vi/uelHwf8o7_U/hq720.jpg',
    views: 1900000000,
    publishedAt: '2010-08-05T00:00:00Z',
    description: '“Love The Way You Lie” – Eminem ft. Rihanna official video.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '4:23',
  },
  {
    id: '60ItHLz5WEA',
    title: 'Alan Walker - Faded',
    channelTitle: 'Alan Walker',
    channelAvatar: 'https://i.pravatar.cc/100?img=37',
    thumbnail: 'https://i.ytimg.com/vi/60ItHLz5WEA/hq720.jpg',
    views: 3400000000,
    publishedAt: '2015-12-03T00:00:00Z',
    description: 'Official music video for “Faded” by Alan Walker.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '3:32',
  },
  {
    id: 'YQHsXMglC9A',
    title: 'Adele - Hello (Live)',
    channelTitle: 'Adele',
    channelAvatar: 'https://i.pravatar.cc/100?img=39',
    thumbnail: 'https://i.ytimg.com/vi/YQHsXMglC9A/hq720.jpg',
    views: 2200000000,
    publishedAt: '2015-10-23T00:00:00Z',
    description: 'Live performance of “Hello” by Adele.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '6:07',
  },
  {
    id: 'fRh_vgS2dFE',
    title: 'Justin Bieber - Sorry',
    channelTitle: 'JustinBieberVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=40',
    thumbnail: 'https://i.ytimg.com/vi/fRh_vgS2dFE/hq720.jpg',
    views: 3700000000,
    publishedAt: '2015-10-22T00:00:00Z',
    description: 'Official music video for “Sorry” by Justin Bieber.',
    tags: ['Trending'],
    category: 'Trending',
    duration: '3:25',
  },
  ],

  Music: [
 {
      id: "kXYiU_JCYtU",
      title: "Linkin Park - Numb",
      channelTitle: "LinkinPark",
      channelAvatar: "https://i.pravatar.cc/100?img=24",
      thumbnail: "https://i.ytimg.com/vi/kXYiU_JCYtU/hq720.jpg",
      views: 2100000000,
      publishedAt: "2007-03-05T00:00:00Z",
      description: "Official music video for 'Numb' by Linkin Park.",
      tags: ["Music"],
      category: "Music",
      duration: "3:07",
    },
    {
      id: "ktvTqknDobU",
      title: "Imagine Dragons - Radioactive",
      channelTitle: "ImagineDragons",
      channelAvatar: "https://i.pravatar.cc/100?img=25",
      thumbnail: "https://i.ytimg.com/vi/ktvTqknDobU/hq720.jpg",
      views: 1400000000,
      publishedAt: "2012-12-10T00:00:00Z",
      description: "Official video for 'Radioactive' by Imagine Dragons.",
      tags: ["Music"],
      category: "Music",
      duration: "3:45",
    },
    {
      id: "YVkUvmDQ3HY",
      title: "Eminem - Without Me",
      channelTitle: "EminemVEVO",
      channelAvatar: "https://i.pravatar.cc/100?img=26",
      thumbnail: "https://i.ytimg.com/vi/YVkUvmDQ3HY/hq720.jpg",
      views: 1700000000,
      publishedAt: "2009-06-16T00:00:00Z",
      description: "Official music video for 'Without Me' by Eminem.",
      tags: ["Music"],
      category: "Music",
      duration: "4:58",
    },
  {
    id: 'hT_nvWreIhg',
    title: 'OneRepublic - Counting Stars',
    channelTitle: 'OneRepublicVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=22',
    thumbnail: 'https://i.ytimg.com/vi/hT_nvWreIhg/hq720.jpg',
    views: 3900000000,
    publishedAt: '2013-05-31T00:00:00Z',
    description: 'OneRepublic’s “Counting Stars” official music video.',
    tags: ['Music'],
    category: 'Music',
    duration: '4:44',
  },
  {
    id: 'fRh_vgS2dFE',
    title: 'Justin Bieber - Sorry',
    channelTitle: 'JustinBieberVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=23',
    thumbnail: 'https://i.ytimg.com/vi/fRh_vgS2dFE/hq720.jpg',
    views: 3700000000,
    publishedAt: '2015-10-22T00:00:00Z',
    description: 'The official video for “Sorry” by Justin Bieber.',
    tags: ['Music'],
    category: 'Music',
    duration: '3:25',
  },
  {
    id: '09R8_2nJtjg',
    title: 'Maroon 5 - Sugar',
    channelTitle: 'Maroon5VEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=24',
    thumbnail: 'https://i.ytimg.com/vi/09R8_2nJtjg/hq720.jpg',
    views: 3900000000,
    publishedAt: '2015-01-14T00:00:00Z',
    description: 'The official music video for “Sugar” by Maroon 5.',
    tags: ['Music'],
    category: 'Music',
    duration: '5:02',
  },
  {
    id: 'ktvTqknDobU',
    title: 'Imagine Dragons - Believer',
    channelTitle: 'ImagineDragonsVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=25',
    thumbnail: 'https://i.ytimg.com/vi/ktvTqknDobU/hq720.jpg',
    views: 2500000000,
    publishedAt: '2017-03-07T00:00:00Z',
    description: 'The official music video for “Believer” by Imagine Dragons.',
    tags: ['Music'],
    category: 'Music',
    duration: '3:37',
  },
  {
    id: 'pRpeEdMmmQ0',
    title: 'Shakira - Waka Waka (This Time for Africa)',
    channelTitle: 'ShakiraVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=26',
    thumbnail: 'https://i.ytimg.com/vi/pRpeEdMmmQ0/hq720.jpg',
    views: 3200000000,
    publishedAt: '2010-06-04T00:00:00Z',
    description: 'Official 2010 FIFA World Cup song “Waka Waka” by Shakira.',
    tags: ['Music'],
    category: 'Music',
    duration: '3:31',
  },
  {
    id: 'SlPhMPnQ58k',
    title: 'Marshmello ft. Bastille - Happier',
    channelTitle: 'Marshmello',
    channelAvatar: 'https://i.pravatar.cc/100?img=27',
    thumbnail: 'https://i.ytimg.com/vi/SlPhMPnQ58k/hq720.jpg',
    views: 1200000000,
    publishedAt: '2018-09-24T00:00:00Z',
    description: 'The official music video for “Happier” by Marshmello and Bastille.',
    tags: ['Music'],
    category: 'Music',
    duration: '3:54',
  },
  {
    id: 'hTWKbfoikeg',
    title: 'Nirvana - Smells Like Teen Spirit',
    channelTitle: 'NirvanaVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=28',
    thumbnail: 'https://i.ytimg.com/vi/hTWKbfoikeg/hq720.jpg',
    views: 1700000000,
    publishedAt: '2009-06-16T00:00:00Z',
    description: 'Official music video for “Smells Like Teen Spirit” by Nirvana.',
    tags: ['Music'],
    category: 'Music',
    duration: '4:38',
  },
  {
    id: '60ItHLz5WEA',
    title: 'Alan Walker - Faded',
    channelTitle: 'Alan Walker',
    channelAvatar: 'https://i.pravatar.cc/100?img=29',
    thumbnail: 'https://i.ytimg.com/vi/60ItHLz5WEA/hq720.jpg',
    views: 3400000000,
    publishedAt: '2015-12-03T00:00:00Z',
    description: 'The official music video for “Faded” by Alan Walker.',
    tags: ['Music'],
    category: 'Music',
    duration: '3:32',
  },
  {
    id: 'CevxZvSJLk8',
    title: 'Katy Perry - Roar',
    channelTitle: 'KatyPerryVEVO',
    channelAvatar: 'https://i.pravatar.cc/100?img=30',
    thumbnail: 'https://i.ytimg.com/vi/CevxZvSJLk8/hq720.jpg',
    views: 3800000000,
    publishedAt: '2013-09-05T00:00:00Z',
    description: 'The official music video for “Roar” by Katy Perry.',
    tags: ['Music'],
    category: 'Music',
    duration: '4:30',
  },
  {
    id: '9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE(강남스타일) M/V',
    channelTitle: 'officialpsy',
    channelAvatar: 'https://i.pravatar.cc/100?img=45',
    thumbnail: 'https://i.ytimg.com/vi/9bZkp7q19f0/hq720.jpg',
    views: 4900000000,
    publishedAt: '2012-07-15T00:00:00Z',
    description: 'The official video for PSY - GANGNAM STYLE.',
    tags: ['Music', 'Trending'],
    category: 'Music',
    duration: '4:13',
  },
  {
    id: 'dQw4w9WgXcQ',
    title: 'Never Gonna Give You Up',
    channelTitle: 'Rick Astley',
    channelAvatar: 'https://i.pravatar.cc/100?img=12',
    thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hq720.jpg',
    views: 1320000000,
    publishedAt: '2009-10-25',
    description: 'The official video for “Never Gonna Give You Up”.',
    tags: ['Music'],
    category: 'Music',
    duration: '3:33',
  },
  ],

  Technology: [
    {
      id: "l9nh1l8ZIJQ",
      title: "iPhone 15 Review: Almost Perfect!",
      channelTitle: "Marques Brownlee",
      channelAvatar: "https://i.pravatar.cc/100?img=12",
      thumbnail: "https://i.ytimg.com/vi/l9nh1l8ZIJQ/hq720.jpg",
      views: 5000000,
      publishedAt: "2023-09-21T00:00:00Z",
      description: "Full in-depth review of the iPhone 15 by MKBHD.",
      tags: ["Technology", "Review"],
      category: "Technology",
      duration: "12:45",
    },
{
  id: 'b6hoBp7Hk-A',
  title: 'Apple Vision Pro – Official Introduction',
  channelTitle: 'Apple',
    channelAvatar: 'https://i.pravatar.cc/100?img=12',
  thumbnail: 'https://i.ytimg.com/vi/b6hoBp7Hk-A/hq720.jpg',
  views: 8900000,
  publishedAt: '2023-06-05T00:00:00Z',
  description: 'Introducing Apple Vision Pro, Apple’s first spatial computer.',
  tags: ['Technology', 'Apple', 'VR'],
  category: 'Technology',
  duration: '9:21'
},
{
  id: 'pXRviuL6vMY',
  title: 'Boston Dynamics Atlas Robot – Parkour and Backflips',
  channelTitle: 'Boston Dynamics',
    channelAvatar: 'https://i.pravatar.cc/100?img=27',
  thumbnail: 'https://i.ytimg.com/vi/pXRviuL6vMY/hq720.jpg',
  views: 42000000,
  publishedAt: '2021-08-17T00:00:00Z',
  description: 'Atlas demonstrates advanced mobility with parkour and backflips.',
  tags: ['Technology', 'Robotics'],
  category: 'Technology',
  duration: '2:28'
},
{
  id: 'tF4DML7FIWk',
  title: 'Atlas | Partners in Parkour',
  channelTitle: 'Boston Dynamics',
      channelAvatar: "https://i.pravatar.cc/100?img=26",
  thumbnail: 'https://i.ytimg.com/vi/tF4DML7FIWk/hq720.jpg',
  views: 3500000,
  publishedAt: '2020-10-11T00:00:00Z',
  description: 'Atlas performs impressive parkour routines in this official Boston Dynamics video.',
  tags: ['Technology', 'Robotics'],
  category: 'Technology',
  duration: '1:00'
},
{
  id: 'oe1dke3Cf7I',
  title: 'Perception and Adaptability | Inside the Lab with Atlas',
  channelTitle: 'Boston Dynamics',
      channelAvatar: "https://i.pravatar.cc/100?img=52",
  thumbnail: 'https://i.ytimg.com/vi/oe1dke3Cf7I/hq720.jpg',
  views: 1200000,
  publishedAt: '2025-06-01T00:00:00Z',
  description: 'A behind-the-scenes look at how Atlas perceives and adapts in real time inside the lab.',
  tags: ['Technology', 'Robotics', 'Research'],
  category: 'Technology',
  duration: '3:45'
},
{
  id: 'I44_zbEwz_w',
  title: 'Walk, Run, Crawl, RL Fun | Boston Dynamics | Atlas',
  channelTitle: 'Boston Dynamics',
    channelAvatar: "https://i.pravatar.cc/100?img=62",
  thumbnail: 'https://i.ytimg.com/vi/I44_zbEwz_w/hq720.jpg',
  views: 4800000,
  publishedAt: '2025-04-10T00:00:00Z',
  description: 'Atlas demonstrates advanced movement policies developed via reinforcement learning.',
  tags: ['Technology', 'Robotics', 'AI'],
  category: 'Technology',
  duration: '2:45'
}

  ],

  Gaming: [
    {
    id: "e-LE0ycgkBQ",
    title: "Minecraft Speedrunner VS 3 Hunters",
    channelTitle: "Dream",
    channelAvatar: "https://i.pravatar.cc/100?img=61",
    thumbnail: "https://i.ytimg.com/vi/e-LE0ycgkBQ/hq720.jpg",
    views: "75M views",
    publishedAt: "Oct 23, 2020",
    description: "Dream attempts to beat Minecraft while three hunters try to stop him.",
    tags: ["Gaming", "Minecraft"],
    category: "Gaming",
    duration: "40:12",
  },
  {
    id: "POmH7dDMDEc",
    title: "Gmod Sandbox – The Toys Escape!",
    channelTitle: "VanossGaming",
    channelAvatar: "https://i.pravatar.cc/100?img=62",
    thumbnail: "https://i.ytimg.com/vi/POmH7dDMDEc/hq720.jpg",
    views: "66M views",
    publishedAt: "Jan 16, 2015",
    description: "Garry’s Mod funny moments: The Toys Escape!",
    tags: ["Gaming", "Funny Moments"],
    category: "Gaming",
    duration: "10:00",
  },
  {
    id: "JldMvQMO_5U",
    title: "Elden Ring – Official Gameplay Reveal",
    channelTitle: "BANDAI NAMCO Europe",
    channelAvatar: "https://i.pravatar.cc/100?img=64",
    thumbnail: "https://i.ytimg.com/vi/JldMvQMO_5U/hq720.jpg",
    views: "7.8M views",
    publishedAt: "Nov 4, 2021",
    description: "Experience a first look at the open world and combat of Elden Ring.",
    tags: ["Gaming", "RPG"],
    category: "Gaming",
    duration: "6:59",
  },
  {
    id: "0E44DClsX5Q",
    title: "Among Us Logic: 100 Players!",
    channelTitle: "GameToons",
    channelAvatar: "https://i.pravatar.cc/100?img=65",
    thumbnail: "https://i.ytimg.com/vi/0E44DClsX5Q/hq720.jpg",
    views: "16M views",
    publishedAt: "Dec 18, 2020",
    description: "A hilarious Among Us animation with 100 crewmates and impostors.",
    tags: ["Gaming", "Among Us", "Animation"],
    category: "Gaming",
    duration: "8:12",
  },
  {
    id: "2gUtfBmw86Y",
    title: "Super Mario Bros. Wonder – Official Trailer",
    channelTitle: "Nintendo",
    channelAvatar: "https://i.pravatar.cc/100?img=67",
    thumbnail: "https://i.ytimg.com/vi/2gUtfBmw86Y/hq720.jpg",
    views: "8.5M views",
    publishedAt: "Jun 21, 2023",
    description: "The official trailer for Super Mario Bros. Wonder, showcasing new worlds, power-ups, and adventures.",
    tags: ["Gaming", "Nintendo", "Super Mario"],
    category: "Gaming",
    duration: "2:44",
  },
    {
      id: "Z1BCujX3pw8",
      title: "Fortnite Chapter 5 Gameplay",
      channelTitle: "Ninja",
      channelAvatar: "https://i.pravatar.cc/100?img=52",
      thumbnail: "https://i.ytimg.com/vi/Z1BCujX3pw8/hq720.jpg",
      views: 7000000,
      publishedAt: "2023-11-18T00:00:00Z",
      description: "Fortnite Chapter 5 gameplay with Ninja.",
      tags: ["Gaming", "Fortnite"],
      category: "Gaming",
      duration: "9:45",
    },
    
  ],
};


const delay = (ms) => new Promise((res) => setTimeout(res, ms));

const allVideos = Object.values(videoData).flat();

export const getVideosByCategory = async (category) => {
  await delay(400);
  if (category === "All") return allVideos;
  return videoData[category] || [];
};

export const searchVideos = async (query) => {
  await delay(400);
  return allVideos.filter((v) =>
    v.title.toLowerCase().includes(query.toLowerCase())
  );
};

export const getVideoById = async (id) => {
  await delay(300);
  return allVideos.find((v) => v.id === id);
};

export const getRelatedVideos = async (id) => {
  await delay(300);
  const video = allVideos.find((v) => v.id === id);
  if (!video) return [];
  return allVideos.filter((v) => v.category === video.category && v.id !== id);
};
